### ISSUE TITLE
Add flag to effects to ignore when calling the dialogue

### ISSUE THREAD

**Issue by p4535992** [GamerFlix/effective-transferral#3]
It is possible to add a flag or something similar for just to activate the module when roll with a specific item ?
I'm asking because I have a lot of objects with active effects, but I would like to use this module only for some of them.

**Comment by GamerFlix** [comment]
That is indeed planned as mentioned [here ](https://github.com/GamerFlix/effective-transferral/issues/2) and I was just going to open an issue to not forget.
I will likely add the flag in the next release and if I can figure out how to add a button the button to set it aswell.

**Comment by p4535992** [comment]
Sorry not see that, i close this ticket because is a duplicate
