### ISSUE TITLE
[v10] Effect isnt activated after using the item.

### ISSUE THREAD

**Issue by vt-tom** [GamerFlix/effective-transferral#33]
After updating to v10 the effect is applied but not activated on the actor.

![grafik](https://user-images.githubusercontent.com/80099175/188608770-12b4cc9a-5153-4d56-a4ae-8eb5a31e3882.png)

**Comment by GamerFlix** [comment]
The effect on your item is disabled and as such will be transferred in a disabled state. This is not an issue with Effective Transferral. If you don't want the effect to be disabled enable it before transferring it.
