### ISSUE TITLE
Mutations cannot be applied if a mutation of the same name already exists

### ISSUE THREAD

**Issue by krbz999** [GamerFlix/effective-transferral#37]
As of WG 1.15.

**Comment by trioderegion** [comment]
While always intended, I never actually took measures to prevent this. Let me know what, if anything, can be added to warpgate's interface to allow this. If i was to add a `looseMatch` kind of parameter, I could auto append a partial `randomID()` (like...4 characters or something -- e.g. `Bless-BEEF`.
