### ISSUE TITLE
Consider a module setting to override `ActiveEffect#origin`

### ISSUE THREAD

**Issue by krbz999** [GamerFlix/effective-transferral#56]
This field is sometimes not set (by users), and sometimes it is. Other modules might rely on it, and being able to better ensure that it is present would help.

**Comment by Adkaiser** [comment]
If I can add to this, it is sometimes helpful to further override the origin to the exact item the effect was transferred from. For example, let's say I am building out a Bless spell. I make it in my Items, and give it a new Temporary Effect. This effect has the origin of the global item. Then, I give the spell to an actor. From testing, it seems like when this effect gets transferred from the actor's item, its origin remains as the global item. However, I'd often rather know the exact instance of that item it came from.
